services:
  - type: web
    name: admin-system-server
    env: node
    rootDir: Server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Set this in Render dashboard to your RDS or Render PostgreSQL
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    plan: free
    healthCheckPath: /healthz
    postDeployCommand: npm run migrate

