services:
  - type: web
    name: admin-system-server
    env: node
    buildCommand: |
      npm --prefix Client install
      npm --prefix Client run build
      npm --prefix Server ci || (cd Server && npm install)
    startCommand: npm --prefix Server start
    envVars:
      - key: NODE_ENV
        value: production
      # Set this in Render dashboard to your RDS or Render PostgreSQL
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    plan: free
    healthCheckPath: /healthz
    postDeployCommand: npm --prefix Server run migrate

